[[manager.prepend_keymap]]
on = ["g", "c"]
run = "cd ~/all/nix-config/"
desc = "Cd to nix config"

[[manager.append_keymap]]
on = ["g", "C"]
run = "cd ~/.config"
desc = "Cd to .config"

[[manager.prepend_keymap]]
on = ["g", "i"]
run = "plugin lazygit"
desc = "run lazygit"
